name: ci-tests

on: [push] # Define when you want this action to run. This is just an example.

jobs:
  checkout_and_pull:
    runs-on: ubuntu-latest
    strategy:
       matrix:
         repo: ['builder', 'io']
    steps:

    - name: Checkout dtcc-platform repos to a separate directory
      uses: actions/checkout@v3
      with:
        repository: dtcc-platform/dtcc-${{ matrix.repo }}
        path: dtcc-${{ matrix.repo }}
        ref: develop

    - name: Merge changes from dtcc-builder into dtcc
      run: |
        pwd 
        ls -alt
        cd dtcc-${{ matrix.repo }}
        git status
        #cp -R dtcc-builder/* . # This copies all files from dtcc-builder to the current directory (dtcc)
        #git add .
        #git commit -m "Merged changes from dtcc-builder
